apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    #k8s-app: ingress-nginx
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/instance: ingress-nginx
    app.kubernetes.io/component: controller
  name: nginx-ingress-controller-metrics
  namespace: monitoring 
spec:
  endpoints:
  - interval: 15s
    port: metrics
  jobLabel: k8s-app
  namespaceSelector:
    matchNames:
    - ingress-controller 
  selector:
    matchLabels:
      app.kubernetes.io/name: ingress-nginx
      app.kubernetes.io/instance: ingress-nginx
      app.kubernetes.io/component: controller
