apiVersion: v1
kind: Service
metadata:
  name: nginx-ingress
  namespace: ingress-controller 
  labels:
    k8s-app: nginx-ingress
  annotations:
    prometheus.io/port: "10254"
    prometheus.io/scrape: "true"
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - name: api
    #port: 9913
    port: 10254
    protocol: TCP
  selector:
    k8s-app: nginx-ingress
    app.kubernetes.io/name: nginx-ingress
    app.kubernetes.io/part-of: nginx-ingress
