apiVersion: v1
kind: Service
metadata:
  name: nginx-ingress-nginx-controller-metrics
  namespace: ingress-controller 
  labels:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/instance: ingress-nginx
    app.kubernetes.io/component: controller
  annotations:
    prometheus.io/port: "10254"
    prometheus.io/scrape: "true"
spec:
  type: ClusterIP
  ports:
  - name: metrics 
    port: 9913
    protocol: TCP
  selector:
    app.kubernetes.io/name: nginx-ingress
    app.kubernetes.io/instance: ingress-nginx
    app.kubernetes.io/component: controller
