kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: ceph-rbd-test
  namespace: cattle-prometheus 
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ceph-rbd
  resources:
    requests:
      storage: 1Gi
