apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
  name: nfs-prometheus 
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: nfs-prometheus
