apiVersion: v1
kind: PersistentVolume
metadata:
  name: monitoring-prometheus-k8s-db-prometheus-k8s-0
  namespace: monitoring
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-prometheus 
