kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nfs-client-prometheus
  annotations:
    volume.beta.kubernetes.io/storage-class: "nfs-client-prometheus"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
