global:
  resolve_timeout: 5m
  smtp_smarthost: 'smtp.qq.com:465'
  smtp_from: '305737438@qq.com'
  smtp_auth_username: 305737438@qq.com
  smtp_auth_password: xijiqyopkrktcbdg #发送邮箱的授权码,非邮箱密码
  smtp_hello: 'qq.com'
  smtp_require_tls: false
  wechat_api_url: 'https://qyapi.weixin.qq.com/cgi-bin/'
  wechat_api_secret: 'XkDEKc-0mQEBVaPrKZRv80CnmV30D7T_E12hg5FKm6U'
  wechat_api_corp_id: 'ww782826ac8ab69a1f'
# 自定义 通知的模板的 目录 或者 文件.
templates:
  - "/etc/alertmanager/config/wechat.tmpl" ##注意：此路径不能更改 
route:
  receiver: wechat
  group_by:
  - alertname
  - cluster
  - service
  group_wait: 30s
  group_interval: 1m  # 当第一个通知发送，等待多久发送压缩的警报
  repeat_interval: 5m #如果报警发送成功, 等待多久重新发送一次
  routes:
  - receiver: wechat 
    match_re:
      severity: critical
  - receiver: email 
    #match:
    #  alertname: CPUThrottlingHigh
    match_re:
      severity: warning 
  - receiver: "null"
    match:
      alertname: Watchdog

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    #equal: ['alertname', 'dev', 'instance']

receivers:
- name: email 
  email_configs:
  - to: '305737438@qq.com'
    headers: { Subject: "报警邮件" } 
    send_resolved: true
- name: 'dingtalk'
  webhook_configs:
  - url: 'http://dingtalk-hook:8060/dingtalk/webhook2/send'
    send_resolved: true
- name: 'wechat'
  wechat_configs:
  - corp_id: 'ww782826ac8ab69a1f'
    to_party: '1' #部门ID
    to_user: "@all"
    agent_id: '1000002'
    api_secret: 'XkDEKc-0mQEBVaPrKZRv80CnmV30D7T_E12hg5FKm6U'
    send_resolved: true
- name: "null"
